In [1]:
from process_data import *
import toggl_api
import pandas as pd
from datetime import datetime as dt

pd.set_option('display.max_columns', None)

start_date=dt(2023, 1, 1)
end_date=dt(2023, 12, 31)
    
# Get the projects and time entries data from the Toggl API
projects = toggl_api.get_projects()
all_time_entries = toggl_api.get_all_time_entries()

In [2]:
pd.DataFrame(all_time_entries).head()

,id,guid,wid,billable,start,stop,duration,tags,duronly,at,uid,pid,description
0,3065685248,05f8108602cd06a3541a4789110fc03f,7464902,True,2023-07-28T08:49:53+00:00,2023-07-28T08:49:53+00:00,0,[Formación / Investigación / Brain Storming],True,2023-07-28T08:50:24+00:00,9577449,NaN,NaN
1,3065685599,7f425c8c8fd4bf04bbcf47a8940480a6,7464902,True,2023-07-28T08:50:41+00:00,2023-07-28T09:01:53+00:00,672,[Formación / Investigación / Brain Storming],True,2023-07-28T09:01:53+00:00,9577449,193974151.0,tirea
2,3065701953,b0506c43093e60922d9881f741a22c89,7464902,True,2023-07-28T09:02:46+00:00,2023-07-28T09:10:16+00:00,450,[Formación / Investigación / Brain Storming],True,2023-07-28T09:10:17+00:00,9577449,193974151.0,NaN
3,3065711298,bf2306761138dc4145d180656a19b268,7464902,False,2023-07-28T09:10:16+00:00,2023-07-28T09:37:35+00:00,1639,NaN,True,2023-07-28T09:37:36+00:00,9577449,NaN,Merge con CLIENT BII y JURI -> isolation en co...
4,3065794638,1626801c56c19950111bde0a7f4183bd,7464902,False,2023-07-28T10:21:21+00:00,2023-07-28T10:46:21+00:00,1500,NaN,True,2023-07-28T10:46:23+00:00,9577449,NaN,NaN

In [3]:
pd.DataFrame(projects)

,id,wid,name,billable,is_private,active,template,at,created_at,color,auto_estimates,currency,hex_color,actual_hours
0,194002072,7464902,Other projects,True,True,True,False,2023-07-30T07:18:06+00:00,2023-07-30T07:18:06+00:00,14,False,USD,#525266,NaN
1,193974620,7464902,Santander,True,True,True,False,2023-07-28T14:41:49+00:00,2023-07-28T08:46:17+00:00,14,False,USD,#525266,2.0
2,193974151,7464902,TIREA,True,True,True,False,2023-07-28T14:41:23+00:00,2023-07-28T08:17:10+00:00,13,False,USD,#d92b2b,NaN

In [4]:
process_data(projects, all_time_entries, start_date, end_date)

KeyError: 'slot_entrie_tags'

In [9]:
# Import the Toggl API functions
import toggl_api

import plotly.express as px
import pandas as pd
from datetime import datetime as dt

min_date_allowed=dt(2023, 1, 1)
max_date_allowed=dt(2025, 12, 31)

# Convert input dates to datetime
start_date = pd.to_datetime(min_date_allowed).tz_localize('UTC')
end_date = pd.to_datetime(max_date_allowed).tz_localize('UTC')

In [67]:
projects = pd.DataFrame(toggl_api.get_projects())

projects.head()

,id,wid,name,billable,is_private,active,template,at,created_at,color,auto_estimates,currency,hex_color
0,193974620,7464902,Santander,True,True,True,False,2023-07-28T14:41:49+00:00,2023-07-28T08:46:17+00:00,14,False,USD,#525266
1,193974151,7464902,TIREA,True,True,True,False,2023-07-28T14:41:23+00:00,2023-07-28T08:17:10+00:00,13,False,USD,#d92b2b

In [68]:
all_time_entries = pd.DataFrame(toggl_api.get_all_time_entries())

all_time_entries.head()

,id,guid,wid,billable,start,stop,duration,tags,duronly,at,uid,pid,description
0,3065685248,05f8108602cd06a3541a4789110fc03f,7464902,True,2023-07-28T08:49:53+00:00,2023-07-28T08:49:53+00:00,0,[Formación / Investigación / Brain Storming],True,2023-07-28T08:50:24+00:00,9577449,NaN,NaN
1,3065685599,7f425c8c8fd4bf04bbcf47a8940480a6,7464902,True,2023-07-28T08:50:41+00:00,2023-07-28T09:01:53+00:00,672,[Formación / Investigación / Brain Storming],True,2023-07-28T09:01:53+00:00,9577449,193974151.0,tirea
2,3065701953,b0506c43093e60922d9881f741a22c89,7464902,True,2023-07-28T09:02:46+00:00,2023-07-28T09:10:16+00:00,450,[Formación / Investigación / Brain Storming],True,2023-07-28T09:10:17+00:00,9577449,193974151.0,NaN
3,3065711298,bf2306761138dc4145d180656a19b268,7464902,False,2023-07-28T09:10:16+00:00,2023-07-28T09:37:35+00:00,1639,NaN,True,2023-07-28T09:37:36+00:00,9577449,NaN,Merge con CLIENT BII y JURI -> isolation en co...
4,3065794638,1626801c56c19950111bde0a7f4183bd,7464902,False,2023-07-28T10:21:21+00:00,2023-07-28T10:46:21+00:00,1500,NaN,True,2023-07-28T10:46:23+00:00,9577449,NaN,NaN

In [69]:
()
    
# Process the data and get the DataFrame
df = process_data(projects, all_time_entries, start_date, end_date)

df.head()

,slot_entrie_id,slot_entrie_guid,slot_entrie_wid,slot_entrie_billable,slot_entrie_start,slot_entrie_stop,slot_entrie_duration,slot_entrie_tags,slot_entrie_duronly,slot_entrie_at,slot_entrie_uid,slot_entrie_pid,slot_entrie_description,project_id,project_wid,project_name,project_billable,project_is_private,project_active,project_template,project_at,project_created_at,project_color,project_auto_estimates,project_currency,project_hex_color
0,3065685248,05f8108602cd06a3541a4789110fc03f,7464902,True,2023-07-28 08:49:53+00:00,2023-07-28 08:49:53+00:00,0,Formación / Investigación / Brain Storming,True,2023-07-28 08:50:24+00:00,9577449,<NA>,No Description,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3065685599,7f425c8c8fd4bf04bbcf47a8940480a6,7464902,True,2023-07-28 08:50:41+00:00,2023-07-28 09:01:53+00:00,672,Formación / Investigación / Brain Storming,True,2023-07-28 09:01:53+00:00,9577449,193974151,tirea,193974151,7464902.0,TIREA,True,True,True,False,2023-07-28T14:41:23+00:00,2023-07-28T08:17:10+00:00,13,False,USD,#d92b2b
2,3065701953,b0506c43093e60922d9881f741a22c89,7464902,True,2023-07-28 09:02:46+00:00,2023-07-28 09:10:16+00:00,450,Formación / Investigación / Brain Storming,True,2023-07-28 09:10:17+00:00,9577449,193974151,No Description,193974151,7464902.0,TIREA,True,True,True,False,2023-07-28T14:41:23+00:00,2023-07-28T08:17:10+00:00,13,False,USD,#d92b2b
3,3065711298,bf2306761138dc4145d180656a19b268,7464902,False,2023-07-28 09:10:16+00:00,2023-07-28 09:37:35+00:00,1639,No Tag,True,2023-07-28 09:37:36+00:00,9577449,<NA>,Merge con CLIENT BII y JURI -> isolation en co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3065794638,1626801c56c19950111bde0a7f4183bd,7464902,False,2023-07-28 10:21:21+00:00,2023-07-28 10:46:21+00:00,1500,No Tag,True,2023-07-28 10:46:23+00:00,9577449,<NA>,No Description,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
def process_descriptions_table_data(projects, all_time_entries, start_date, end_date):
    # Convierte la lista de entradas de tiempo y proyectos en DataFrames
    slot_entries_df = pd.DataFrame(all_time_entries)
    projects_df = pd.DataFrame(projects)

    # Resto de tu código preexistente para preprocesar los DataFrames...
    
    # Define el intervalo de fechas y conviértelo a UTC
    tz = pytz.timezone('UTC')
    start_date = pd.to_datetime(start_date).tz_localize(None).tz_localize(tz)
    end_date = pd.to_datetime(end_date).tz_localize(None).tz_localize(tz)
    
    # Filtra los datos por el intervalo temporal deseado
    mask = (slot_entries_df['slot_entrie_start'] >= start_date) & (slot_entries_df['slot_entrie_stop'] <= end_date)
    filtered_slot_entries_df = slot_entries_df.loc[mask]
    
    # Merge con projects_df
    merged_df = filtered_slot_entries_df.merge(projects_df, left_on='slot_entrie_pid', right_on='project_id', how='left')
    print(merged_df)
    # Rellena los valores NaN en la columna 'project_name' con 'Other'
    merged_df['project_name'] = merged_df['project_name'].fillna('Other projects')

    # Calcula el tiempo total para el intervalo de tiempo seleccionado
    total_time = merged_df['total_hours'].sum()

    # Crea un DataFrame con las columnas 'project_name', 'slot_entrie_description' y 'total_hours'
    summary_df = merged_df[['project_name', 'slot_entrie_description', 'total_hours']]

    # Agrupa por 'project_name' y 'slot_entrie_description' y suma 'total_hours'
    summary_df = summary_df.groupby(['project_name', 'slot_entrie_description']).sum().reset_index()

    # Calcula el porcentaje de tiempo dedicado a cada tarea
    summary_df['percentage'] = (summary_df['total_hours'] / total_time) * 100

    # Ordena el DataFrame por 'percentage' en orden descendente
    summary_df = summary_df.sort_values(by='percentage', ascending=False)

    return summary_df  # Devuelve el nuevo DataFrame

In [77]:
process_descriptions_table_data(projects, all_time_entries, start_date, end_date)

          id      wid            name  billable  is_private  active  template  \
0  194002072  7464902  Other projects      True        True    True     False
1  193974620  7464902       Santander      True        True    True     False
2  193974151  7464902           TIREA      True        True    True     False

                          at                 created_at color  auto_estimates  \
0  2023-07-30T07:18:06+00:00  2023-07-30T07:18:06+00:00    14           False
1  2023-07-28T14:41:49+00:00  2023-07-28T08:46:17+00:00    14           False
2  2023-07-28T14:41:23+00:00  2023-07-28T08:17:10+00:00    13           False

  currency hex_color  actual_hours
0      USD   #525266           NaN
1      USD   #525266           2.0
2      USD   #d92b2b           NaN

KeyError: 'slot_entrie_start'